"""Add index to cat_personalities faction_id

Revision ID: 144e0687d0a9
Revises: c04b1fbdddc9
Create Date: 2026-01-12 02:06:29.463336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144e0687d0a9'
down_revision: Union[str, None] = 'c04b1fbdddc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually cleaned to only add the index
    with op.batch_alter_table('cat_personalities', schema=None) as batch_op:
        batch_op.create_index('idx_cat_personalities_faction', ['faction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat_personalities', schema=None) as batch_op:
        batch_op.drop_index('idx_cat_personalities_faction')
    # ### end Alembic commands ###

