"""add messages_archive table

Revision ID: 19e354bbe1ad
Revises: 705586abe9c3
Create Date: 2026-01-11 18:00:12.775326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e354bbe1ad'
down_revision: Union[str, None] = '705586abe9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Manual Cleanup: Only create messages_archive ###
    op.create_table('messages_archive',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages_archive', schema=None) as batch_op:
        batch_op.create_index('idx_archive_created', ['created_at'], unique=False)
        batch_op.create_index('idx_archive_room', ['room_id'], unique=False)

    # Note: Ignoring other schema drift (cat tables, users.is_bot) to prevent breakage.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages_archive', schema=None) as batch_op:
        batch_op.drop_index('idx_archive_room')
        batch_op.drop_index('idx_archive_created')

    op.drop_table('messages_archive')
    # ### end Alembic commands ###
