"""add admin_ops table

Revision ID: c04b1fbdddc9
Revises: 19e354bbe1ad
Create Date: 2026-01-11 18:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04b1fbdddc9'
down_revision: Union[str, None] = '19e354bbe1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Manual Cleanup: Only create admin_ops ###
    op.create_table('admin_ops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_ops', schema=None) as batch_op:
        batch_op.create_index('idx_admin_ops_admin', ['admin_id'], unique=False)
        batch_op.create_index('idx_admin_ops_created', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_ops', schema=None) as batch_op:
        batch_op.drop_index('idx_admin_ops_created')
        batch_op.drop_index('idx_admin_ops_admin')

    op.drop_table('admin_ops')
    # ### end Alembic commands ###
