"""Add report indices

Revision ID: f5888d5eac95
Revises: 4ac599a4d562
Create Date: 2026-01-09 01:07:24.138867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5888d5eac95'
down_revision: Union[str, None] = '4ac599a4d562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_reports_reporter', ['reporter_id'], unique=False)
        batch_op.create_index('idx_reports_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('idx_reports_status')
        batch_op.drop_index('idx_reports_reporter')
    # ### end Alembic commands ###
